#pragma once
#include "ICM_20948.h"
// Calibration functions generated by ChatGPT

#define CALIBRATION_FLAG_ADDR 0
#define MAG_OFFSET_ADDR 10
#define ACC_OFFSET_ADDR 40

struct Vec3 {
    float x, y, z;
};

Vec3 magOffset = {0,0,0};
Vec3 accOffset = {0,0,0};

void saveCalibrationData() {
    EEPROM.put(MAG_OFFSET_ADDR, magOffset);
    EEPROM.put(ACC_OFFSET_ADDR, accOffset);
    uint8_t flag = 0xA5;
    EEPROM.put(CALIBRATION_FLAG_ADDR, flag);
}

bool loadCalibrationData() {
    uint8_t flag;
    EEPROM.get(CALIBRATION_FLAG_ADDR, flag);
    if (flag == 0xA5) {
        EEPROM.get(MAG_OFFSET_ADDR, magOffset);
        EEPROM.get(ACC_OFFSET_ADDR, accOffset);
        return true;
    }
    return false;
}

void calibrateIMU(ICM_20948 *imu) {
    Particle.publish("IMU", "Starting calibration...");
    Serial.println("Starting calibration...");
    unsigned long start = millis();
    const unsigned long duration = 30000; // 30 seconds

    float magMin[3] = {9999, 9999, 9999};
    float magMax[3] = {-9999, -9999, -9999};
    float accMin[3] = {9999, 9999, 9999};
    float accMax[3] = {-9999, -9999, -9999};

    Particle.publish("IMU", "Move sensor in all directions!");
    Serial.println("Move sensor in all directions!");

    while (millis() - start < duration) {
        if (imu->dataReady()) {
            imu->getAGMT();

            float mx = imu->magX();
            float my = imu->magY();
            float mz = imu->magZ();
            float ax = imu->accX();
            float ay = imu->accY();
            float az = imu->accZ();

            magMin[0] = fmin(magMin[0], mx);
            magMin[1] = fmin(magMin[1], my);
            magMin[2] = fmin(magMin[2], mz);
            magMax[0] = fmax(magMax[0], mx);
            magMax[1] = fmax(magMax[1], my);
            magMax[2] = fmax(magMax[2], mz);

            accMin[0] = fmin(accMin[0], ax);
            accMin[1] = fmin(accMin[1], ay);
            accMin[2] = fmin(accMin[2], az);
            accMax[0] = fmax(accMax[0], ax);
            accMax[1] = fmax(accMax[1], ay);
            accMax[2] = fmax(accMax[2], az);
        }
        delay(20);
    }

    magOffset.x = (magMax[0] + magMin[0]) / 2.0f;
    magOffset.y = (magMax[1] + magMin[1]) / 2.0f;
    magOffset.z = (magMax[2] + magMin[2]) / 2.0f;

    accOffset.x = (accMax[0] + accMin[0]) / 2.0f;
    accOffset.y = (accMax[1] + accMin[1]) / 2.0f;
    accOffset.z = (accMax[2] + accMin[2]) / 2.0f;

    saveCalibrationData();

    char msg[128];
    snprintf(msg, sizeof(msg), "Calibration complete. Mag offsets: %.2f, %.2f, %.2f", magOffset.x, magOffset.y, magOffset.z);
    Serial.println(msg);
    Particle.publish("IMU", msg);
}